name: set-step-output
description: |
  Set the output for this step to any text value.
author: "Street Side Software <info@streetsidesoftware.nl>"
inputs:
  value:
    description: The value to return.
    required: true
  debug:
    description: Show the value in the console.
    required: false
outputs:
  value:
    description: The value that was input.
    value: ${{ inputs.value }}
runs:
  using: "composite"
  steps:
    - name: Debug
      if: inputs.debug
      shell: bash
      env:
        VALUE: ${{ inputs.value }}
      run: |
        echo "$VALUE"
